// frontend_next/src/components/TacticalDesk.tsx
'use client'

import React, { useState } from 'react'
import { useDashboard } from '@/context/DashboardContext'
import { useI18n } from '@/i18n/context'
import { Layers, Clock, ShieldCheck, ArrowUpRight, ArrowDownRight, Trash2 } from 'lucide-react'

export function TacticalDesk() {
  const { positions, orders } = useDashboard()
  const { t } = useI18n()
  const [activeSubTab, setActiveSubTab] = useState<'positions' | 'orders'>('positions')

  return (
    <div className="rounded-lg border shadow-xs overflow-hidden bg-[#121317] border-[#242630]">
      {/* Sub Tabs */}
      <div className="px-3 py-2 border-b flex items-center justify-between bg-[#17181e] border-[#242630]">
        <div className="flex items-center space-x-2">
          <button
            onClick={() => setActiveSubTab('positions')}
            className={`px-3 py-1 rounded text-xs font-mono font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
              activeSubTab === 'positions'
                ? 'bg-[#f3f4f6] text-[#0a0b0e]'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>{t.activePositions} ({positions.length})</span>
          </button>

          <button
            onClick={() => setActiveSubTab('orders')}
            className={`px-3 py-1 rounded text-xs font-mono font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
              activeSubTab === 'orders'
                ? 'bg-[#f3f4f6] text-[#0a0b0e]'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Clock className="w-3.5 h-3.5" />
            <span>{t.pendingOrders} ({orders.length})</span>
          </button>
        </div>

        <div className="text-[10px] font-mono text-emerald-400 flex items-center gap-1">
          <ShieldCheck className="w-3 h-3 text-emerald-400" />
          <span>100% OCO CLOUD PROTECTION</span>
        </div>
      </div>

      {/* POSITIONS TABLE */}
      {activeSubTab === 'positions' && (
        <div className="overflow-x-auto min-h-[140px]">
          {positions.length === 0 ? (
            <div className="py-10 text-center text-xs font-mono text-slate-500">
              {t.noPositions}
            </div>
          ) : (
            <table className="w-full text-left text-xs font-mono whitespace-nowrap">
              <thead>
                <tr className="border-b text-[10px] uppercase text-slate-400 bg-[#0e0f13] border-[#242630]">
                  <th className="py-2 px-3">{t.instrument}</th>
                  <th className="py-2 px-2">{t.direction}</th>
                  <th className="py-2 px-2">{t.entryPrice}</th>
                  <th className="py-2 px-2">{t.markPrice}</th>
                  <th className="py-2 px-2">{t.margin}</th>
                  <th className="py-2 px-2">{t.unrealizedPnl}</th>
                  <th className="py-2 px-2">{t.tpPrice}</th>
                  <th className="py-2 px-2">{t.slPrice}</th>
                  <th className="py-2 px-3 text-right">{t.action}</th>
                </tr>
              </thead>
              <tbody>
                {positions.map((p: any) => {
                  const isLong = p.side === 'long'
                  const upl = Number(p.upl || p.unrealized_pnl || 0)
                  return (
                    <tr key={p.posId || p.instId} className="border-b last:border-b-0 hover:bg-[#1e2028] border-[#242630]">
                      <td className="py-2 px-3 font-bold text-slate-200">
                        {p.instId || p.symbol}
                      </td>
                      <td className="py-2 px-2">
                        <span className={`px-1.5 py-0.2 rounded text-[10px] font-bold border ${
                          isLong
                            ? 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30'
                            : 'text-rose-400 bg-rose-500/10 border-rose-500/30'
                        }`}>
                          {isLong ? 'LONG 多' : 'SHORT 空'} {p.lever || p.leverage}x
                        </span>
                      </td>
                      <td className="py-2 px-2 tabular-nums text-slate-300">{p.avgPx || p.entry_price}</td>
                      <td className="py-2 px-2 tabular-nums text-slate-300">{p.markPx || p.mark_price || '--'}</td>
                      <td className="py-2 px-2 tabular-nums text-indigo-300">${p.margin || p.margin_usdt || '--'}</td>
                      <td className={`py-2 px-2 tabular-nums font-bold ${upl >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                        {upl >= 0 ? '+' : ''}${upl.toFixed(2)}
                      </td>
                      <td className="py-2 px-2 tabular-nums text-emerald-400">{p.tpPx || p.tp_price || '--'}</td>
                      <td className="py-2 px-2 tabular-nums text-rose-400">{p.slPx || p.sl_price || '--'}</td>
                      <td className="py-2 px-3 text-right">
                        <button
                          onClick={() => alert('Fast Close Token Verification')}
                          className="px-2 py-0.5 rounded border text-[10px] text-rose-400 border-rose-500/30 bg-rose-500/10 hover:bg-rose-500/20 cursor-pointer"
                        >
                          {t.closePosition}
                        </button>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          )}
        </div>
      )}

      {/* ORDERS TABLE */}
      {activeSubTab === 'orders' && (
        <div className="overflow-x-auto min-h-[140px]">
          {orders.length === 0 ? (
            <div className="py-10 text-center text-xs font-mono text-slate-500">
              {t.noOrders}
            </div>
          ) : (
            <table className="w-full text-left text-xs font-mono whitespace-nowrap">
              <thead>
                <tr className="border-b text-[10px] uppercase text-slate-400 bg-[#0e0f13] border-[#242630]">
                  <th className="py-2 px-3">{t.instrument}</th>
                  <th className="py-2 px-2">类型</th>
                  <th className="py-2 px-2">{t.direction}</th>
                  <th className="py-2 px-2">委托价</th>
                  <th className="py-2 px-2">数量</th>
                  <th className="py-2 px-2">触发条件</th>
                  <th className="py-2 px-3 text-right">{t.action}</th>
                </tr>
              </thead>
              <tbody>
                {orders.map((o: any) => (
                  <tr key={o.ordId} className="border-b last:border-b-0 hover:bg-[#1e2028] border-[#242630]">
                    <td className="py-2 px-3 font-bold text-slate-200">{o.instId}</td>
                    <td className="py-2 px-2 text-slate-400">{o.ordType || 'LIMIT'}</td>
                    <td className="py-2 px-2">
                      <span className={`px-1.5 py-0.2 rounded text-[10px] font-bold ${
                        o.side === 'buy' ? 'text-emerald-400' : 'text-rose-400'
                      }`}>
                        {o.side?.toUpperCase()}
                      </span>
                    </td>
                    <td className="py-2 px-2 tabular-nums text-slate-300">{o.px || '--'}</td>
                    <td className="py-2 px-2 tabular-nums text-slate-300">{o.sz || '--'}</td>
                    <td className="py-2 px-2 text-slate-400">{o.tpTriggerPx ? `TP: ${o.tpTriggerPx}` : (o.slTriggerPx ? `SL: ${o.slTriggerPx}` : '--')}</td>
                    <td className="py-2 px-3 text-right">
                      <button className="p-1 rounded text-rose-400 hover:opacity-80">
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  )
}

// frontend/src/components/TacticalDesk.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useDashboardStore } from '../stores/dashboard'
import { useI18nStore } from '../stores/i18n'
import {
  ShieldCheck,
  ShieldAlert,
  Layers,
  Clock,
  Activity,
} from 'lucide-vue-next'

const store = useDashboardStore()
const i18n = useI18nStore()

const activeTab = ref<'positions' | 'orders'>('positions')
const selectedSymbol = ref<string>('ALL')

const availableSymbols = computed(() => {
  const set = new Set<string>()
  store.positions.forEach((p) => {
    const s = p.name || p.instId.split('-')[0]
    if (s) set.add(s)
  })
  store.pendingOrders.forEach((o) => {
    const s = o.name || o.instId.split('-')[0]
    if (s) set.add(s)
  })
  return ['ALL', ...Array.from(set)]
})

const filteredPositions = computed(() => {
  return store.positions.filter((p) => {
    const sym = p.name || p.instId.split('-')[0]
    return selectedSymbol.value === 'ALL' || sym === selectedSymbol.value
  })
})

const filteredOrders = computed(() => {
  return store.pendingOrders.filter((o) => {
    const sym = o.name || o.instId.split('-')[0]
    return selectedSymbol.value === 'ALL' || sym === selectedSymbol.value
  })
})

function fmt2(v: any): string {
  const n = typeof v === 'number' ? v : parseFloat(String(v ?? ''))
  return Number.isFinite(n) ? n.toFixed(2) : '--'
}

function fmt4(v: any): string {
  const n = typeof v === 'number' ? v : parseFloat(String(v ?? ''))
  if (!Number.isFinite(n)) return '--'
  return n >= 100 ? n.toFixed(2) : String(parseFloat(n.toFixed(4)))
}

const allProtected = computed(() =>
  store.positions.length > 0 &&
  store.positions.every(
    (p: any) =>
      p.protectionStatus === 'fully_protected' ||
      Number(p.protectionCoveragePct || 0) >= 100
  )
)
</script>

<template>
  <div
    class="rounded-xl border transition-all shadow-xs overflow-hidden font-mono"
    style="background-color: var(--bg-card); border-color: var(--border-subtle);"
  >
    <!-- Tactical Desk Header Ribbon -->
    <div
      class="px-3 sm:px-4 py-2 border-b flex flex-wrap items-center justify-between gap-2.5"
      style="border-color: var(--border-subtle); background-color: var(--bg-card-subtle);"
    >
      <!-- Left: Desk Tabs Switcher -->
      <div class="flex items-center space-x-1 p-0.5 rounded border text-xs" style="background-color: var(--bg-card); border-color: var(--border-subtle);">
        <button
          @click="activeTab = 'positions'"
          class="h-7 flex items-center space-x-1.5 px-2.5 rounded font-bold transition-all cursor-pointer"
          :style="activeTab === 'positions'
            ? { backgroundColor: 'var(--text-main)', color: 'var(--bg-app)' }
            : { color: 'var(--text-muted)' }"
        >
          <Activity class="w-3.5 h-3.5" />
          <span>{{ i18n.t.activePositions }}</span>
          <span
            class="px-1.5 py-0.2 rounded-full text-[10px] font-bold"
            :style="activeTab === 'positions'
              ? { backgroundColor: 'var(--bg-app)', color: 'var(--text-main)' }
              : { backgroundColor: 'var(--bg-badge)', color: 'var(--text-muted)' }"
          >
            {{ store.positions.length }}
          </span>
        </button>

        <button
          @click="activeTab = 'orders'"
          class="h-7 flex items-center space-x-1.5 px-2.5 rounded font-bold transition-all cursor-pointer"
          :style="activeTab === 'orders'
            ? { backgroundColor: 'var(--text-main)', color: 'var(--bg-app)' }
            : { color: 'var(--text-muted)' }"
        >
          <Clock class="w-3.5 h-3.5" />
          <span>{{ i18n.t.pendingOrders }}</span>
          <span
            class="px-1.5 py-0.2 rounded-full text-[10px] font-bold"
            :style="activeTab === 'orders'
              ? { backgroundColor: 'var(--bg-app)', color: 'var(--text-main)' }
              : { backgroundColor: 'var(--bg-badge)', color: 'var(--text-muted)' }"
          >
            {{ store.pendingOrders.length }}
          </span>
        </button>
      </div>

      <!-- Right: Search & Protection Indicator -->
      <div class="flex items-center space-x-2">
        <div class="hidden sm:flex items-center space-x-1">
          <button
            v-for="sym in availableSymbols"
            :key="sym"
            @click="selectedSymbol = sym"
            class="h-6.5 px-2 rounded text-[10px] font-bold transition-all cursor-pointer border"
            :style="selectedSymbol === sym
              ? { backgroundColor: 'var(--bg-badge)', borderColor: 'var(--border-medium)', color: 'var(--text-main)' }
              : { borderColor: 'transparent', color: 'var(--text-muted)' }"
          >
            {{ sym }}
          </button>
        </div>

        <!-- Cloud OCO Status Badge -->
        <div
          class="h-7 flex items-center space-x-1 text-[11px] px-2 rounded border font-bold"
          :style="{
            backgroundColor: allProtected ? 'var(--color-up-bg)' : 'var(--color-warn-bg)',
            borderColor: allProtected ? 'var(--color-up-border)' : 'var(--color-warn-border)',
            color: allProtected ? 'var(--color-up)' : 'var(--color-warn)'
          }"
        >
          <ShieldCheck v-if="allProtected" class="w-3 h-3" />
          <ShieldAlert v-else class="w-3 h-3" />
          <span>{{ allProtected ? (i18n.locale === 'zh' ? '100% 云端止损保护' : '100% Cloud OCO Protected') : (i18n.locale === 'zh' ? '部分仓位未设止损' : 'Partially Unprotected') }}</span>
        </div>
      </div>
    </div>

    <!-- TAB CONTENT 1: POSITIONS -->
    <div v-if="activeTab === 'positions'">
      <div v-if="filteredPositions.length === 0" class="py-12 text-center rounded-b-xl border-dashed">
        <div
          class="w-10 h-10 mx-auto mb-2 rounded-xl flex items-center justify-center border"
          style="background-color: var(--bg-card-subtle); border-color: var(--border-subtle); color: var(--text-muted);"
        >
          <Layers class="w-4 h-4" />
        </div>
        <p class="text-xs" style="color: var(--text-muted);">
          {{ i18n.t.noPositions }}
        </p>
      </div>

      <div v-else class="overflow-x-auto">
        <table class="w-full text-left text-xs whitespace-nowrap">
          <thead>
            <tr
              class="text-[10px] uppercase tracking-wider border-b"
              style="background-color: var(--bg-card-subtle); border-color: var(--border-subtle); color: var(--text-muted);"
            >
              <th class="py-2.5 px-3 font-bold">{{ i18n.locale === 'zh' ? '标的 / 杠杆' : 'Asset / Lev' }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.t.direction }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.t.positionSize }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.t.entryPrice }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.t.markPrice }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.locale === 'zh' ? '保证金占用' : 'Margin' }}</th>
              <th class="py-2.5 px-3 text-right font-bold">{{ i18n.locale === 'zh' ? '未结盈亏' : 'UPL / ROE' }}</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="pos in filteredPositions"
              :key="pos.instId"
              class="border-b last:border-b-0 transition-colors hover:bg-[var(--bg-card-hover)]"
              style="border-color: var(--border-subtle);"
            >
              <!-- 标的 / 杠杆 -->
              <td class="py-2.5 px-3">
                <div class="flex items-center space-x-1.5">
                  <span class="font-black text-xs tracking-wide" style="color: var(--text-main);">
                    {{ pos.name }}
                  </span>
                  <span
                    class="px-1 py-0.2 rounded text-[9px] font-bold border"
                    style="background-color: var(--bg-badge); color: var(--text-main); border-color: var(--border-subtle);"
                  >
                    {{ pos.lever }}x
                  </span>
                </div>
              </td>

              <!-- 方向 -->
              <td class="py-2.5 px-3">
                <span
                  class="px-1.5 py-0.2 rounded text-[10px] font-bold inline-flex items-center space-x-1 border"
                  :style="{
                    backgroundColor: pos.side === 'long' ? 'var(--color-up-bg)' : 'var(--color-down-bg)',
                    borderColor: pos.side === 'long' ? 'var(--color-up-border)' : 'var(--color-down-border)',
                    color: pos.side === 'long' ? 'var(--color-up)' : 'var(--color-down)'
                  }"
                >
                  <span>{{ pos.side === 'long' ? i18n.t.actionBuy : i18n.t.actionSell }}</span>
                </span>
              </td>

              <!-- 持仓量 -->
              <td class="py-2.5 px-3 font-bold num-tabular" style="color: var(--text-main);">
                {{ pos.pos }} <span class="text-[10px] font-normal" style="color: var(--text-faint);">{{ i18n.locale === 'zh' ? '张' : 'cont' }}</span>
              </td>

              <!-- 开仓均价 -->
              <td class="py-2.5 px-3 num-tabular" style="color: var(--text-muted);">
                ${{ fmt2(pos.avgPx) }}
              </td>

              <!-- 标记市价 -->
              <td class="py-2.5 px-3 font-black text-xs num-tabular" style="color: var(--text-main);">
                ${{ fmt4(pos.markPx ?? pos.last) }}
              </td>

              <!-- 实际保证金 -->
              <td class="py-2.5 px-3 num-tabular" style="color: var(--text-main);">
                ${{ fmt2(pos.margin_usdt ?? pos.margin) }}
              </td>

              <!-- 未结盈亏 -->
              <td class="py-2.5 px-3 text-right">
                <div
                  class="font-black text-xs num-tabular"
                  :style="{ color: Number(pos.upl) >= 0 ? 'var(--color-up)' : 'var(--color-down)' }"
                >
                  {{ Number(pos.upl) >= 0 ? '+' : '' }}${{ fmt2(pos.upl) }}
                </div>
                <div
                  class="text-[10px] font-bold num-tabular"
                  :style="{ color: Number(pos.uplRatio ?? pos.roe_pct ?? 0) >= 0 ? 'var(--color-up)' : 'var(--color-down)' }"
                >
                  {{ Number(pos.uplRatio ?? pos.roe_pct ?? 0) >= 0 ? '+' : '' }}{{ Number(pos.uplRatio ?? pos.roe_pct ?? 0).toFixed(2) }}%
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- TAB CONTENT 2: PENDING ORDERS -->
    <div v-else>
      <div v-if="filteredOrders.length === 0" class="py-12 text-center rounded-b-xl border-dashed">
        <div
          class="w-10 h-10 mx-auto mb-2 rounded-xl flex items-center justify-center border"
          style="background-color: var(--bg-card-subtle); border-color: var(--border-subtle); color: var(--text-muted);"
        >
          <Clock class="w-4 h-4" />
        </div>
        <p class="text-xs" style="color: var(--text-muted);">
          {{ i18n.t.noOrders }}
        </p>
      </div>

      <div v-else class="overflow-x-auto">
        <table class="w-full text-left text-xs whitespace-nowrap">
          <thead>
            <tr
              class="text-[10px] uppercase tracking-wider border-b"
              style="background-color: var(--bg-card-subtle); border-color: var(--border-subtle); color: var(--text-muted);"
            >
              <th class="py-2.5 px-3 font-bold">{{ i18n.t.symbol }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.t.direction }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.locale === 'zh' ? '委托类型' : 'Type' }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.locale === 'zh' ? '委托价' : 'Order Px' }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.locale === 'zh' ? '委托量' : 'Size' }}</th>
              <th class="py-2.5 px-3 font-bold">{{ i18n.t.tradeTime }}</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="ord in filteredOrders"
              :key="ord.ordId"
              class="border-b last:border-b-0 transition-colors hover:bg-[var(--bg-card-hover)]"
              style="border-color: var(--border-subtle);"
            >
              <td class="py-2.5 px-3 font-bold text-slate-200">{{ ord.instId }}</td>
              <td class="py-2.5 px-3 font-bold" :class="ord.side === 'buy' ? 'text-emerald-400' : 'text-rose-400'">
                {{ ord.side === 'buy' ? i18n.t.actionBuy : i18n.t.actionSell }}
              </td>
              <td class="py-2.5 px-3 text-slate-400 uppercase text-[10px]">{{ ord.ordType }}</td>
              <td class="py-2.5 px-3 num-tabular text-slate-200">${{ ord.px || '--' }}</td>
              <td class="py-2.5 px-3 num-tabular text-slate-200">{{ ord.sz }}</td>
              <td class="py-2.5 px-3 text-slate-500 text-[10px]">{{ ord.cTime || '--' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>
