// frontend_next/src/components/TopHudRibbon.tsx
'use client'

import React from 'react'
import { useDashboard } from '@/context/DashboardContext'
import { useI18n } from '@/i18n/context'
import { Wallet, TrendingUp, Activity, ShieldCheck } from 'lucide-react'

export function TopHudRibbon() {
  const { account, todayStats, positions } = useDashboard()
  const { t } = useI18n()

  const totalEq = Number(account?.total_eq || 0).toFixed(2)
  const availEq = Number(account?.avail_eq || 0).toFixed(2)
  const marginUsage = Number(account?.margin_usage_pct || 0).toFixed(1)

  const benchmarkNetPnl = Number(account?.cum_net_pnl || 0).toFixed(2)
  const benchmarkRoi = Number(account?.cum_roi_pct || 0).toFixed(2)
  const initialCap = Number(account?.initial_capital || 0).toFixed(2)

  const todayNet = Number(todayStats?.net_realized ?? todayStats?.total_pnl ?? 0).toFixed(2)
  const todayWinrate = Number(todayStats?.win_rate || 0).toFixed(1)
  const todayTrades = (todayStats?.win_trades || 0) + (todayStats?.loss_trades || 0)

  const posUplNum = Number(account?.pos_upl_total ?? account?.upl ?? 0)
  const posUplStr = posUplNum.toFixed(2)

  const longCount = positions.filter((p: any) => p.side === 'long').length
  const shortCount = positions.filter((p: any) => p.side === 'short').length

  return (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-2 text-xs font-mono select-none">
      {/* 1. Master Equity */}
      <div className="rounded-lg border px-3 py-2 flex flex-col justify-between shadow-xs bg-[#121317] border-[#242630]">
        <div className="flex items-center justify-between text-[10px] text-slate-400">
          <span className="flex items-center gap-1 font-bold text-slate-300">
            <Wallet className="w-3 h-3 text-indigo-400" />
            <span>{t.masterEquity}</span>
          </span>
          <span className="text-[9px] px-1 rounded border border-slate-700 bg-slate-800 text-slate-400">OKX PROD</span>
        </div>
        <div className="flex items-baseline justify-between mt-1">
          <div className="text-lg lg:text-xl font-black tracking-tight tabular-nums text-slate-100">
            ${totalEq}
          </div>
          <div className="text-[11px] text-slate-500">
            {t.availBalance}: <span className="font-bold text-slate-200">${availEq}</span>
          </div>
        </div>
        <div className="w-full h-1 rounded-full overflow-hidden mt-1.5 bg-[#1c1e26]">
          <div
            className="h-full rounded-full transition-all duration-500"
            style={{
              width: `${Math.min(100, Math.max(0, Number(marginUsage)))}%`,
              backgroundColor: Number(marginUsage) > 50 ? '#f59e0b' : '#10b981',
            }}
          />
        </div>
      </div>

      {/* 2. Benchmark ROI */}
      <div className="rounded-lg border px-3 py-2 flex flex-col justify-between shadow-xs bg-[#121317] border-[#242630]">
        <div className="flex items-center justify-between text-[10px] text-slate-400">
          <span className="flex items-center gap-1 font-bold text-slate-300">
            <TrendingUp className="w-3 h-3 text-emerald-400" />
            <span>{t.benchmarkRoi}</span>
          </span>
          <span className={`text-[10px] tabular-nums font-bold ${Number(benchmarkNetPnl) >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
            {Number(benchmarkRoi) >= 0 ? '+' : ''}{benchmarkRoi}%
          </span>
        </div>
        <div className="flex items-baseline justify-between mt-1">
          <div className={`text-lg lg:text-xl font-black tracking-tight tabular-nums ${Number(benchmarkNetPnl) >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
            {Number(benchmarkNetPnl) >= 0 ? '+' : ''}${benchmarkNetPnl}
          </div>
          <div className="text-[11px] text-slate-500">
            {t.initialCapital}: <span className="font-bold text-slate-300">${initialCap}</span>
          </div>
        </div>
        <div className="text-[10px] mt-1.5 truncate text-slate-500">
          P0 Hard Floor: 2.0R Geometry Lock
        </div>
      </div>

      {/* 3. Session Performance */}
      <div className="rounded-lg border px-3 py-2 flex flex-col justify-between shadow-xs bg-[#121317] border-[#242630]">
        <div className="flex items-center justify-between text-[10px] text-slate-400">
          <span className="flex items-center gap-1 font-bold text-slate-300">
            <Activity className="w-3 h-3 text-amber-400" />
            <span>{t.sessionPerf}</span>
          </span>
          <span className="text-[10px] font-bold text-slate-300">
            {t.winRate} {todayWinrate}%
          </span>
        </div>
        <div className="flex items-baseline justify-between mt-1">
          <div className={`text-lg lg:text-xl font-black tracking-tight tabular-nums ${Number(todayNet) >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
            {Number(todayNet) >= 0 ? '+' : ''}${todayNet}
          </div>
          <div className="text-[11px] text-slate-500">
            {t.todayTrades}: <span className="font-bold text-slate-200">{todayTrades} {t.tradesCount}</span>
          </div>
        </div>
        <div className="text-[10px] mt-1.5 flex items-center justify-between text-slate-500">
          <span>W: <strong className="text-emerald-400">{todayStats?.win_trades || 0}</strong></span>
          <span>L: <strong className="text-rose-400">{todayStats?.loss_trades || 0}</strong></span>
          <span>R:R: <strong className="text-slate-200">{todayStats?.profit_factor || '2.0+'}</strong></span>
        </div>
      </div>

      {/* 4. Unrealized UPL & Risk Sentinel */}
      <div className="rounded-lg border px-3 py-2 flex flex-col justify-between shadow-xs bg-[#121317] border-[#242630]">
        <div className="flex items-center justify-between text-[10px] text-slate-400">
          <span className="flex items-center gap-1 font-bold text-slate-300">
            <ShieldCheck className="w-3 h-3 text-blue-400" />
            <span>{t.unrealizedUpl}</span>
          </span>
          <span className="text-[10px] font-bold text-emerald-400">100% OCO CLOUD</span>
        </div>
        <div className="flex items-baseline justify-between mt-1">
          <div className={`text-lg lg:text-xl font-black tracking-tight tabular-nums ${posUplNum >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
            {posUplNum >= 0 ? '+' : ''}${posUplStr}
          </div>
          <div className="text-[11px] text-slate-500">
            {positions.length} {t.positionsCount}
          </div>
        </div>
        <div className="text-[10px] mt-1.5 flex items-center justify-between text-slate-500">
          <span>Long: <strong className="text-emerald-400">{longCount}</strong></span>
          <span>Short: <strong className="text-rose-400">{shortCount}</strong></span>
          <span>Protection: <strong className="text-emerald-400">FAIL-CLOSED</strong></span>
        </div>
      </div>
    </div>
  )
}

// frontend/src/components/TopHudRibbon.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useDashboardStore } from '../stores/dashboard'
import { Wallet, TrendingUp, ShieldCheck, Activity, Layers, ArrowUpRight, ArrowDownRight } from 'lucide-vue-next'

const store = useDashboardStore()
const account = computed(() => store.data?.account || {})
const today = computed(() => store.data?.today_stats || {})

const totalEq = computed(() => Number(account.value.total_eq || 0).toFixed(2))
const availEq = computed(() => Number(account.value.avail_eq || 0).toFixed(2))
const marginUsage = computed(() => Number(account.value.margin_usage_pct || 0).toFixed(1))

const benchmarkNetPnl = computed(() => Number(account.value.cum_net_pnl || 0).toFixed(2))
const benchmarkRoi = computed(() => Number(account.value.cum_roi_pct || 0).toFixed(2))
const initialCap = computed(() => Number(account.value.initial_capital || 0).toFixed(2))

const todayNet = computed(() => Number(today.value.net_realized ?? today.value.total_pnl ?? 0).toFixed(2))
const todayWinrate = computed(() => Number(today.value.win_rate || 0).toFixed(1))
const todayTrades = computed(() => (today.value.win_trades || 0) + (today.value.loss_trades || 0))

const posUplNum = computed(() => Number(account.value.pos_upl_total ?? account.value.upl ?? 0))
const posUplStr = computed(() => posUplNum.value.toFixed(2))

const longCount = computed(() => store.positions.filter((p) => p.side === 'long').length)
const shortCount = computed(() => store.positions.filter((p) => p.side === 'short').length)
</script>

<template>
  <!-- Institutional High-Density Compact HUD Ribbon (4 Metrics in 1 Uniform Row) -->
  <div class="grid grid-cols-2 lg:grid-cols-4 gap-2 text-xs font-mono select-none">
    <!-- Block 1: Master Equity & Margin Usage -->
    <div
      class="rounded-lg border px-3 py-2 flex flex-col justify-between shadow-xs transition-colors"
      style="background-color: var(--bg-card); border-color: var(--border-subtle);"
    >
      <div class="flex items-center justify-between text-[10px]" style="color: var(--text-muted);">
        <span class="flex items-center gap-1 font-bold text-slate-300">
          <Wallet class="w-3 h-3 text-indigo-400" />
          <span>MASTER EQUITY</span>
        </span>
        <span class="text-[9px] px-1 rounded border border-slate-700 bg-slate-800 text-slate-400">OKX PROD</span>
      </div>
      <div class="flex items-baseline justify-between mt-1">
        <div class="text-lg lg:text-xl font-black tracking-tight num-tabular" style="color: var(--text-main);">
          ${{ totalEq }}
        </div>
        <div class="text-[11px] text-right" style="color: var(--text-faint);">
          可用: <span class="font-bold text-slate-200">${{ availEq }}</span>
        </div>
      </div>
      <div class="w-full h-1 rounded-full overflow-hidden mt-1.5" style="background-color: var(--bg-badge);">
        <div
          class="h-full rounded-full transition-all duration-500"
          :style="{
            width: `${Math.min(100, Math.max(0, Number(marginUsage)))}%`,
            backgroundColor: Number(marginUsage) > 50 ? 'var(--color-warn)' : '#10b981'
          }"
        ></div>
      </div>
    </div>

    <!-- Block 2: Benchmark Net ROI / PnL -->
    <div
      class="rounded-lg border px-3 py-2 flex flex-col justify-between shadow-xs transition-colors"
      style="background-color: var(--bg-card); border-color: var(--border-subtle);"
    >
      <div class="flex items-center justify-between text-[10px]" style="color: var(--text-muted);">
        <span class="flex items-center gap-1 font-bold text-slate-300">
          <TrendingUp class="w-3 h-3 text-emerald-400" />
          <span>BENCHMARK CUMULATIVE</span>
        </span>
        <span class="text-[10px] num-tabular" :class="Number(benchmarkNetPnl) >= 0 ? 'text-emerald-400' : 'text-rose-400'">
          {{ Number(benchmarkRoi) >= 0 ? '+' : '' }}{{ benchmarkRoi }}%
        </span>
      </div>
      <div class="flex items-baseline justify-between mt-1">
        <div class="text-lg lg:text-xl font-black tracking-tight num-tabular" :class="Number(benchmarkNetPnl) >= 0 ? 'text-emerald-400' : 'text-rose-400'">
          {{ Number(benchmarkNetPnl) >= 0 ? '+' : '' }}${{ benchmarkNetPnl }}
        </div>
        <div class="text-[11px] text-right" style="color: var(--text-faint);">
          基准本金: <span class="font-bold text-slate-300">${{ initialCap }}</span>
        </div>
      </div>
      <div class="text-[10px] mt-1.5 truncate" style="color: var(--text-faint);">
        基准锚点: 2026-03 策略重塑基线
      </div>
    </div>

    <!-- Block 3: Today's Realized Performance -->
    <div
      class="rounded-lg border px-3 py-2 flex flex-col justify-between shadow-xs transition-colors"
      style="background-color: var(--bg-card); border-color: var(--border-subtle);"
    >
      <div class="flex items-center justify-between text-[10px]" style="color: var(--text-muted);">
        <span class="flex items-center gap-1 font-bold text-slate-300">
          <Activity class="w-3 h-3 text-amber-400" />
          <span>SESSION PERFORMANCE</span>
        </span>
        <span class="text-[10px] font-bold text-slate-300">胜率 {{ todayWinrate }}%</span>
      </div>
      <div class="flex items-baseline justify-between mt-1">
        <div class="text-lg lg:text-xl font-black tracking-tight num-tabular" :class="Number(todayNet) >= 0 ? 'text-emerald-400' : 'text-rose-400'">
          {{ Number(todayNet) >= 0 ? '+' : '' }}${{ todayNet }}
        </div>
        <div class="text-[11px] text-right" style="color: var(--text-faint);">
          今日成交: <span class="font-bold text-slate-200">{{ todayTrades }} 笔</span>
        </div>
      </div>
      <div class="text-[10px] mt-1.5 flex items-center justify-between" style="color: var(--text-faint);">
        <span>胜: <strong class="text-emerald-400">{{ today.win_trades || 0 }}</strong></span>
        <span>负: <strong class="text-rose-400">{{ today.loss_trades || 0 }}</strong></span>
        <span>盈亏比: <strong class="text-slate-200">{{ today.profit_factor || '2.0+' }}</strong></span>
      </div>
    </div>

    <!-- Block 4: Live Floating Exposure & Risk Protection -->
    <div
      class="rounded-lg border px-3 py-2 flex flex-col justify-between shadow-xs transition-colors"
      style="background-color: var(--bg-card); border-color: var(--border-subtle);"
    >
      <div class="flex items-center justify-between text-[10px]" style="color: var(--text-muted);">
        <span class="flex items-center gap-1 font-bold text-slate-300">
          <ShieldCheck class="w-3 h-3 text-blue-400" />
          <span>UNREALIZED UPL</span>
        </span>
        <span class="text-[10px] font-bold text-emerald-400">100% OCO CLOUD</span>
      </div>
      <div class="flex items-baseline justify-between mt-1">
        <div class="text-lg lg:text-xl font-black tracking-tight num-tabular" :class="posUplNum >= 0 ? 'text-emerald-400' : 'text-rose-400'">
          {{ posUplNum >= 0 ? '+' : '' }}${{ posUplStr }}
        </div>
        <div class="text-[11px] text-right" style="color: var(--text-faint);">
          持仓: <span class="font-bold text-slate-200">{{ store.positions.length }} 笔</span>
        </div>
      </div>
      <div class="text-[10px] mt-1.5 flex items-center justify-between" style="color: var(--text-faint);">
        <span>多头: <strong class="text-emerald-400">{{ longCount }}</strong></span>
        <span>空头: <strong class="text-rose-400">{{ shortCount }}</strong></span>
        <span>未结保护: <strong class="text-emerald-400">FAIL-CLOSED</strong></span>
      </div>
    </div>
  </div>
</template>
